### ISSUE TITLE
urllib2.HTTPError: HTTP Error 414: Request-URI Too Large

### ISSUE THREAD

**Issue by tramaraj** [cschu/ktoolu#1]
Hi - 

I am trying to use the script kt_summarize.py to plot Kraken output with Krona. For some kraken report files it works fine, but from some kraken output files I get the following error message,

python ktoolu/kt_summarize.py --draw-krona-plot KRONA_PLOT.html --path-to-krona kronatools/KronaTools-2.6/bin/ --write-summary KRONA_SUMMARY kraken-report.txt
Traceback (most recent call last):
  File "ktoolu/kt_summarize.py", line 122, in <module>
    if **name** == '**main**': main()
  File "ktoolu/kt_summarize.py", line 81, in main
    taxInfoDict = {tinfo['TaxId']: [tinfo, taxCounter[tinfo['TaxId']]] for tinfo in fetchTaxonomyData(taxids)}
  File "ktoolu/kt_summarize.py", line 38, in fetchTaxonomyData
    handle = Entrez.efetch(db='Taxonomy', id=','.join(ids), retmode='xml')
  File "/sw/python/2.7.1/lib/python2.7/site-packages/Bio/Entrez/**init**.py", line 139, in efetch
    return _open(cgi, variables)
  File "/sw/python/2.7.1/lib/python2.7/site-packages/Bio/Entrez/__init__.py", line 455, in _open
    raise exception
urllib2.HTTPError: HTTP Error 414: Request-URI Too Large

Any thoughts on how to get this rectified.

Thank You.
TR

**Comment by cschu** [comment]
Hi TR

do you maybe have a lot of tax ids in your output? That could explain 
it, as kt_summarize.py communicates with NCBI-Taxonomy to obtain 
taxonomy labels. In that case it is clearly a bug and I need to put some 
time into fixing it. Could you provide me the kraken classification file 
by chance?

Sorry about the bug.

Best
Christian
